server:
  port: 8080
  servlet:
    context-path: /
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/fitness_db
    username: postgres
    password: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
jwt:
  private_secret: nurewijtlgj4eiwiutfwoiuiurYTGKJBVB6575675464654GHJKBYIYUBBKUBIUOIkj3y4tfrnn234inu23oi4ruo23iur2n3or
  access_token_lifetime: 3600000
  refresh_token_lifetime: 86400000
errors:
  wrong_username_or_password: Неправильное имя пользователя ил пароль.
  token_expired: Истек срок действия токена.
  invalid_signature: Некорректная подпись.
